# monitor,test/data.yml

server:
  port: ${MONITOR_PORT:9100}
  servlet:
    context-path: /monitor

spring:
  # 授权账号/密码
  security:
    user:
      name: admin
      password: admin

  boot:
    admin:
      # 上下文路径
      # 在静态资产（assets）和API路径的前面加上前缀，相对于Dispatcher-Servlet
      context-path: /monitor

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
