# user-biz,dev/data.yml

server:
  port: ${USER_BIZ_PORT:9200}

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    # 指定使用的数据源
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 池中最大连接数（包括空闲和正在使用的连接）
      maximum-pool-size: 5
      # 池中最小空闲连接数量
      minimum-idle: 1

  # 多数据源配置
  multiple-datasource:
    # master
    - name: master
      driver-class-name: ${spring.datasource.driver-class-name}
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      type: ${spring.datasource.type}
      hikari:
        maximum-pool-size: ${spring.datasource.hikari.maximum-pool-size}
        minimum-idle: ${spring.datasource.hikari.minimum-idle}

    # slave
    - name: slave
      driver-class-name: ${spring.datasource.driver-class-name}
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      type: ${spring.datasource.type}
      hikari:
        maximum-pool-size: ${spring.datasource.hikari.maximum-pool-size}
        minimum-idle: ${spring.datasource.hikari.minimum-idle}

  # redis配置
  redis:
    # 服务器地址
    host: 127.0.0.1
    # 服务器端口
    port: 6379
    # 服务器密码，如果没有设置密码则可以省略
    #password:
    # 数据库编号，默认为0
    database: 0
    # 连接超时时间（单位：毫秒），默认为2000ms
    timeout: 60000
    # 使用Lettuce作为客户端
    lettuce:
      pool:
        # 连接池中的最小空闲连接数，默认为0
        min-idle: 2
        # 连接池中的最大空闲连接数，默认为8
        max-idle: 8
        # 连接池中的最大连接数，默认为8
        max-active: 8
      # 连接池关闭的超时时间（单位：毫秒），默认为100ms
      shutdown-timeout: 60000

# 监控配置：actuator
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    # org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointProperties
    web:
      exposure:
        include: '*'
    # org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointProperties
    jmx:
      exposure:
        include: '*'

# 线程池配置
thread:
  pool:
    # 线程池中核心线程数量
    # 线程池中始终保持存活的线程数量，即使这些线程处于空闲状态，也不会被回收
    core-pool-size: 6
    # 线程池中最大线程数量
    # 线程池中允许存在的最大线程数量，当工作队列已满且当前线程数小于最大线程数时，会创建新线程来处理任务
    maximum-pool-size: 12
    # 线程池中非核心线程闲置超时时间，时间格式：{n}h{n}m{n}s
    keep-alive-time: 60s
    # 工作队列容量
    work-queue-capacity: 1024
    # 拒绝策略
    rejected-execution-handler-class-name: java.util.concurrent.ThreadPoolExecutor$AbortPolicy
