spring:
  cloud:
    gateway:
      discovery:
        # org.springframework.cloud.gateway.discovery.DiscoveryLocatorProperties
        locator:
          # 表明gateway开启服务注册和发现的功能
          # 并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          enabled: true
          # 路由id前缀
          route-id-prefix: ReactiveCompositeDiscoveryClient_
          # 是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了
          lower-case-service-id: true

      # 路由配置
      #routes:
      #  - id: ${spring.cloud.gateway.discovery.locator.route-id-prefix}user
      #    # lb代表从注册中心获取服务
      #    uri: lb://user
      #    predicates:
      #      # 转发路径
      #      - Path=/user/**
      #    # 过滤器
      #    filters:
      #      # StripPrefix的作用是去掉前缀的，值即对应层数
      #      - StripPrefix=1
