# monitor,dev/data.yml

server:
  port: ${MONITOR_PORT:9100}

spring:
  # 授权账号/密码
  security:
    user:
      name: admin
      password: admin

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
