spring:
  # 模板配置
  thymeleaf:
    # Thymeleaf的模板位置，默认值：classpath:/templates/
    prefix: classpath:/templates/
    # 匹配后缀
    suffix: .html
    # 模板模式
    mode1: HTML5
    # 模板编码
    encoding: UTF-8
    # 是否使用页面缓存
    cache: false
