# gateway/data.yml

spring:
  cloud:
    gateway:
      discovery:
        # 服务发现定位器（locator），可以自动根据服务发现的信息为每个服务创建路由规则（router）
        # org.springframework.cloud.gateway.discovery.DiscoveryLocatorProperties
        locator:
          # 启用了服务发现的定位器（locator）
          enabled: true
          # 路由id前缀
          route-id-prefix: ReactiveCompositeDiscoveryClient_
          # 将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了）
          lower-case-service-id: true
