spring:
  redis:
    # Redis基础配置
    # Redis服务器地址
    host: ${REDIS_HOST:redis}
    # Redis服务器连接端口
    port: ${REDIS_PORT:6379}
    # Redis服务器连接密码（默认为空）
    #password:
    # Redis数据库索引（默认为0）
    database: 0
    # 集群
    #cluster:
    #  nodes: 192.168.1.11:6379, 192.168.1.12:6379, 192.168.1.13:6379
    # 连接超时时间（ms）
    timeout: 5000

    # Redis Lettuce配置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中最小空闲连接数
        min-idle: 0
        # 连接池中最小空闲连接数
        max-idle: 8
        # 连接池最大阻塞等待时间（ms）（使用负值表示没有限制）
        max-wait: 5000

# resilience4j
resilience4j:
  # io.github.resilience4j.retry.RetryConfig
  retry:
    configs:
      default:
        # 最大尝试次数，默认3次
        maxAttempts: 3
        # 重试间隔时间
        waitDuration: 10s
        # 是否允许使用指数退避算法进行重试间隔时间的计算
        #enableExponentialBackoff: false
        #exponentialBackoffMultiplier: 2     # 指数退避算法的乘数
        #enableRandomizedWait: false       # 是否允许使用随机的重试间隔
        #randomizedWaitFactor: 0.5         # 随机因子
        #retryExceptions:
        #  - im.marlinlm.exception.RetryException     #触发重试的异常类
        #ignoreExceptions:
        #  - im.marlinlm.exception.RetryIgnoredException     #不会触发重试的异常类
    instances:
      myRetry:
        baseConfig: default
        waitDuration: 1 #1毫秒，最小等待时间为1毫秒

      flightSearch:
        maxRetryAttempts: 3
        waitDuration: 2s
